// Моковые данные для тестирования интерфейса
export const mockStudents = [
  {
    id: 1,
    full_name: 'Александр Петров',
    photo_url: 'https://i.pravatar.cc/150?img=11',
    course: 2,
    department: 'Кафедра общей физики',
    location: 'Лаборатория оптики, 5-18',
    bio: 'Помогаю с лабораторными по оптике и термеху. Сам проходил пересдачу, знаю все подводные камни. Могу объяснить тензорный анализ простыми словами.',
    tags: ['оптика', 'термех', 'матан', 'помощь', 'пересдача'],
    is_mentor: true,
    trust_score: 4.8,
    help_count: 23,
    last_active: new Date().toISOString(),
    match_probability: 0.94,
    match_reasons: ['Совпадение по курсу', 'Оба в ГЗ', 'Шарит в оптике'],
  },
  {
    id: 2,
    full_name: 'Мария Иванова',
    photo_url: 'https://i.pravatar.cc/150?img=5',
    course: 3,
    department: 'Кафедра квантовой механики',
    location: 'ГЗ, 4 этаж, читальный зал',
    bio: 'Работаю в лаборатории квантовых технологий. Помогаю с квантовой механикой и диффурами. Есть опыт стажировки в Яндексе.',
    tags: ['квантовая физика', 'диффуры', 'работа', 'стажировка', 'ML'],
    is_mentor: true,
    trust_score: 4.9,
    help_count: 41,
    last_active: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    match_probability: 0.89,
    match_reasons: ['Старшекурсник', 'Есть опыт работы'],
  },
  {
    id: 3,
    full_name: 'Дмитрий Соколов',
    photo_url: 'https://i.pravatar.cc/150?img=3',
    course: 4,
    department: 'Кафедра вычислительной физики',
    location: 'Физфак, коворкинг',
    bio: 'Пишу на Python, C++, знаю ML. Помогаю с программированием и проектами. Работаю в Сбере, могу рассказать про собесы.',
    tags: ['python', 'c++', 'ML', 'работа', 'программирование'],
    is_mentor: true,
    trust_score: 4.7,
    help_count: 56,
    last_active: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    match_probability: 0.85,
    match_reasons: ['Помощь с кодом', 'Знает про работу'],
  },
  {
    id: 4,
    full_name: 'Елена Козлова',
    photo_url: 'https://i.pravatar.cc/150?img=9',
    course: 2,
    department: 'Кафедра общей физики',
    location: 'Лаборатория фотоники',
    bio: 'Прошла комиссию по физике, знаю как подготовиться. Помогаю с конспектами и лабами. Ищу компанию для совместной подготовки.',
    tags: ['физика', 'конспекты', 'комиссия', 'подготовка'],
    is_mentor: true,
    trust_score: 4.5,
    help_count: 12,
    last_active: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    match_probability: 0.82,
    match_reasons: ['Один курс', 'Похожие проблемы'],
  },
  {
    id: 5,
    full_name: 'Андрей Новиков',
    photo_url: 'https://i.pravatar.cc/150?img=13',
    course: 5,
    department: 'Кафедра астрофизики',
    location: 'ОИЯИ, Дубна',
    bio: 'Занимаюсь высокопроизводительными вычислениями в ОИЯИ. Помогаю с матаном, термехом, квантами. Могу взять на проект.',
    tags: ['вычисления', 'астрофизика', 'матан', 'проект', 'ОИЯИ'],
    is_mentor: true,
    trust_score: 4.9,
    help_count: 78,
    last_active: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    match_probability: 0.78,
    match_reasons: ['Опыт проектов', 'Помощь с матаном'],
  },
  {
    id: 6,
    full_name: 'Анна Морозова',
    photo_url: 'https://i.pravatar.cc/150?img=10',
    course: 3,
    department: 'Кафедра психологии',
    location: 'ГЗ, сектор Б',
    bio: 'Прошла через выгорание на физфаке. Сейчас помогаю другим справиться со стрессом. Знаю про психологическую помощь в МГУ.',
    tags: ['психология', 'выгорание', 'помощь', 'стресс', 'МГУ'],
    is_mentor: true,
    trust_score: 4.8,
    help_count: 34,
    last_active: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    match_probability: 0.75,
    match_reasons: ['Эмоциональная поддержка'],
  },
]

export const mockChats = [
  {
    id: 1,
    participant: mockStudents[0],
    last_message: 'Спасибо большое за помощь с лабой!',
    last_message_time: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    unread_count: 2,
  },
  {
    id: 2,
    participant: mockStudents[1],
    last_message: 'Можем встретиться в читалке на 4 этаже',
    last_message_time: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    unread_count: 0,
  },
  {
    id: 3,
    participant: mockStudents[2],
    last_message: 'Отправил тебе резюме на проверку',
    last_message_time: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    unread_count: 0,
  },
]

export const mockMessages = [
  {
    id: 1,
    sender_id: 1,
    text: 'Привет! Увидел, что ты шаришь в оптике. Можешь помочь с лабой?',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 2,
    sender_id: 'me',
    text: 'Привет! Да, конечно. Что именно не получается?',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
  },
  {
    id: 3,
    sender_id: 1,
    text: 'Не сходится погрешность в третьей работе. Уже всё перепроверил',
    timestamp: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
  {
    id: 4,
    sender_id: 'me',
    text: 'А, это классика! Там часто забывают про систематическую погрешность прибора',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 5,
    sender_id: 1,
    text: 'Спасибо большое за помощь с лабой!',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
]

export const mockCurrentUser = {
  id: 100,
  full_name: 'Елизавета',
  photo_url: 'https://i.pravatar.cc/150?img=20',
  course: 2,
  department: 'Физический факультет',
  location: 'ГЗ',
  bio: 'Ищу помощь с учебой и хочу помогать другим!',
  tags: ['физика', 'матан', 'помощь'],
  telegram_username: '@elizaveta',
  trust_score: 0,
  help_count: 0,
}
